// <auto-generated />
using ComicViewer.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComicViewer.Migrations
{
    [DbContext(typeof(ComicContext))]
    partial class ComicContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("ComicViewer.Models.ComicData", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("MD5主键");

                    b.HasKey("Key");

                    b.ToTable("Comics");
                });

            modelBuilder.Entity("ComicViewer.Models.ComicTag", b =>
                {
                    b.Property<string>("ComicKey")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("漫画MD5外键");

                    b.Property<string>("TagKey")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("标签MD5外键");

                    b.HasKey("ComicKey", "TagKey");

                    b.HasIndex("ComicKey");

                    b.HasIndex("TagKey");

                    b.ToTable("ComicTags");
                });

            modelBuilder.Entity("ComicViewer.Models.TagModel", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("MD5主键");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("ComicViewer.Models.ComicTag", b =>
                {
                    b.HasOne("ComicViewer.Models.ComicData", "Comic")
                        .WithMany("ComicTags")
                        .HasForeignKey("ComicKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComicViewer.Models.TagModel", "Tag")
                        .WithMany("ComicTags")
                        .HasForeignKey("TagKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comic");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ComicViewer.Models.ComicData", b =>
                {
                    b.Navigation("ComicTags");
                });

            modelBuilder.Entity("ComicViewer.Models.TagModel", b =>
                {
                    b.Navigation("ComicTags");
                });
#pragma warning restore 612, 618
        }
    }
}
