// <auto-generated />
using System;
using ComicViewer.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComicViewer.Migrations
{
    [DbContext(typeof(ComicContext))]
    [Migration("20251212063904_Add_Source")]
    partial class Add_Source
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("ComicViewer.Models.ComicData", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(32)
                        .HasColumnType("VARCHAR(32)")
                        .HasColumnName("Key")
                        .HasComment("MD5主键");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("DATETIME")
                        .HasColumnName("CreatedTime")
                        .HasComment("创建时间");

                    b.Property<DateTime>("LastAccess")
                        .HasColumnType("DATETIME")
                        .HasColumnName("LastAccess")
                        .HasComment("最后访问时间");

                    b.Property<int>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("Progress")
                        .HasComment("阅读进度");

                    b.Property<int>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("Rating")
                        .HasComment("评分 0-5");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Source")
                        .HasComment("漫画源");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("Title")
                        .HasComment("漫画标题");

                    b.HasKey("Key");

                    b.ToTable("Comics", (string)null);
                });

            modelBuilder.Entity("ComicViewer.Models.ComicTag", b =>
                {
                    b.Property<string>("ComicKey")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("ComicKey")
                        .HasComment("漫画MD5外键");

                    b.Property<string>("TagKey")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("TagKey")
                        .HasComment("标签MD5外键");

                    b.HasKey("ComicKey", "TagKey");

                    b.HasIndex("ComicKey");

                    b.HasIndex("TagKey");

                    b.ToTable("ComicTags");
                });

            modelBuilder.Entity("ComicViewer.Models.MovingFileModel", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("Key");

                    b.Property<string>("DestinationPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Dst");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Src");

                    b.HasKey("Key");

                    b.ToTable("MovingFiles", (string)null);
                });

            modelBuilder.Entity("ComicViewer.Models.TagData", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(32)
                        .HasColumnType("VARCHAR(32)")
                        .HasColumnName("Key")
                        .HasComment("MD5主键");

                    b.Property<int>("Count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("Count");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.HasKey("Key");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("ComicViewer.Models.ComicTag", b =>
                {
                    b.HasOne("ComicViewer.Models.ComicData", "Comic")
                        .WithMany("ComicTags")
                        .HasForeignKey("ComicKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComicViewer.Models.TagData", "Tag")
                        .WithMany("ComicTags")
                        .HasForeignKey("TagKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comic");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ComicViewer.Models.MovingFileModel", b =>
                {
                    b.HasOne("ComicViewer.Models.ComicData", "Comic")
                        .WithOne()
                        .HasForeignKey("ComicViewer.Models.MovingFileModel", "Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comic");
                });

            modelBuilder.Entity("ComicViewer.Models.ComicData", b =>
                {
                    b.Navigation("ComicTags");
                });

            modelBuilder.Entity("ComicViewer.Models.TagData", b =>
                {
                    b.Navigation("ComicTags");
                });
#pragma warning restore 612, 618
        }
    }
}
